<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="Fast_Faults_Evaluate" Id="{b174bc0b-1725-058a-3694-8cbdd4b2c6db}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Fast_Faults_Evaluate
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[g_FastFaultOutput1.EvaluateOutput();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>