<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PMPS" Id="{9f17630a-fcaa-08bb-22bb-9b109c090d19}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PMPS
VAR
    
    fbArbiterIO : FB_SubSysToArbiter_IO;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbArbiterIO(Arbiter := GVL.g_fbArbiter1, fbFFHWO := GVL.g_FastFaultOutput1);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>